dist: xenial
language: python
notifications:
  email: false
python:
  - "3.6"
  - "3.7"
script:
  - pip install -qq flake8 mypy
  - pip install -qq -e '.[tests]'
  - flake8 ./docargs  # this also checks docargs!
  - mypy docargs --ignore-missing-imports
