language: python
notifications:
  email: false
python:
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
script:
  - pip install -qq flake8 coverage coveralls mypy
  - mypy docargs
  - pip install -qq -e '.[tests]'
  - coverage run -m flake8 docargs
  - coveralls