language: python
notifications:
  email: false
python:
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
script:
  - pip install -qq flake8 mypy
  - mypy docargs --ignore-missing-imports
  - pip install -qq -e '.[tests]'
  - flake8 ./docargs
